# Generated by Django 5.2 on 2025-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated required skills'),
        ),
    ]
