# Generated by Django 5.2 on 2025-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
    ]
